export const INIITIALISE = "INITIALISE"
export const ADDCATEGORY = "ADDCATEGORY"

export const ADDPRODUCT = "ADDPRODUCT"

export const DELETEPRODUCT = "DELETEPRODUCT"

export const ADDEMPLOYEE = "ADDEMPLOYEE"
export const ADDTABLE  = "ADDTABLE"

export const ADDAUTHENTICATE = "ADDAUTHENTICATE"

export  const INITIALISEDORDERS = "INITIALISEDORDERS"

export const ADDNEWORDER = "ADDNEWORDER"